var Evema={Core:{},Modules:{},QueuePosition:0,Queue:[],OnIndexLoad:function(){var a=Evema;a.QueuePosition=0;a.Queue=[{name:"Tools",path:"core/Tools"},{name:"Generator",path:"core/Generator"},{name:"Power",path:"core/Power"},{name:"Grid",path:"core/Grid"},{name:"ContextMenu",path:"core/ContextMenu"},{name:"Schema",path:"core/Schema"}];a.Init()},Init:function(){var a=Evema;console.log("Initializing modules");for(var b=a.Queue,c=b.length,d=0;d<c;d++)console.log('Initializing "'+b[d].name+'"...'),a.Eval(b[d].name+
":Init");console.log("Initializing complete")},Has:function(a){return void 0!==Evema.Modules[a]},Eval:function(a,b){var c=Evema,d=a.split(":");2!==d.length?console.warn('Unknown action type "'+a+'"'):(a=d[0],c="@"===a?c:c.Modules[a],void 0===c?console.warn('Module "'+a+'" not found'):(c=c.Actions,void 0===c?console.warn('Module "'+a+'" has no actions'):(d=d[1],c=c[d],void 0!==c?c(b):console.warn('Unknown "'+a+'" action "'+d+'"'))))},Set:function(a,b){var c=Evema,d=a.split(":");if(2!==d.length)console.warn('Unknown option type "'+
a+'"');else if(a=d[0],c="@"===a?c:c.Modules[a],void 0===c)console.warn('Module "'+a+'" not found');else{var e=c.Options;if(void 0===e)console.warn('Module "'+a+'" has no options');else if(d=d[1],e.Setters&&void 0!==e.Setters[d])e.Setters[d](c,b);else e.Current[d]=b}},Get:function(a){var b=Evema,c=a.split(":");if(2!==c.length)console.warn('Unknown option type "'+a+'"');else{a=c[0];var d="@"===a?b:b.Modules[a];if(void 0===d)console.warn('Module "'+a+'" not found');else if(b=d.Options,void 0===b)console.warn('Module "'+
a+'" has no options');else{c=c[1];if(b.Getters&&void 0!==b.Getters[c])return b.Getters[c](d);a=b.Current[c];return void 0!==a?a:b.Standard[c]}}},EvalLocal:function(a,b,c){a&&a.Actions&&(a=a.Actions[b],void 0!==a&&a(c))},SetLocal:function(a,b,c){if(a&&a.Options){var d=a.Options;if(d.Setters&&void 0!==d.Setters[b])d.Setters[b](a,c);else d.Current[b]=c}},GetLocal:function(a,b){if(a&&a.Options){var c=a.Options;if(c.Getters&&void 0!==c.Getters[b])return c.Getters[b](a);a=c.Current[b];return void 0!==a?
a:c.Standard[b]}},Actions:{},Options:{Standard:{},Current:{}}};window.onload=Evema.OnIndexLoad;
Evema.Modules.Tools=function(){var a={List:[{class:"file-tool",func:"Evema.Eval('Tools:File')"},{class:"element-tool",func:"Evema.Eval('Tools:Element')"},{class:"power-tool",func:"Evema.Eval('Tools:Power')"},{class:"generator-tool",func:"Evema.Eval('Tools:Generator')"},{class:"about-tool",func:"Evema.Eval('Tools:About')"},{class:"options-tool",func:"Evema.Eval('Tools:Options')"},{class:"exit-tool",func:"Evema.Eval('Tools:Exit')"}],Init:function(){var b=$(".tools")[0];Evema.SetLocal(a,"Panel",b);for(var c=
a.List.length,d={tools__show:$(".tools__show").attr("onclick","Evema.Eval('Tools:ShowPanel')")[0],tools__hide:$(".tools__hide").attr("onclick","Evema.Eval('Tools:HidePanel')")[0]},e=0;e<c;e++){b.appendChild(document.createElement("HR"));var f=document.createElement("BUTTON");$(f).addClass("tools__button").addClass(a.List[e].class).attr("onclick",a.List[e].func);d[a.List[e].class]=f;b.appendChild(f)}Evema.SetLocal(a,"Buttons",d)},HidePanel:function(){var b=Evema.GetLocal(a,"Panel"),c=Evema.GetLocal(a,
"Buttons").tools__show;$(b).addClass("hidden");$(c).addClass("active")},ShowPanel:function(){var b=Evema.GetLocal(a,"Panel"),c=Evema.GetLocal(a,"Buttons").tools__show;$(b).removeClass("hidden");$(c).removeClass("active")},File:function(){console.log("Tools.File not implemented")},Element:function(){console.log("Tools.Element not implemented")},Power:function(){Evema.Eval("Power:Toggle")},Generator:function(){Evema.Eval("Generator:Toggle")},OptionsFunc:function(){console.log("Tools.OptionsFunc not implemented")},
About:function(){console.log("Tools.About not implemented")},Exit:function(){window.close()},Options:{Standard:{Buttons:{},Panel:{}},Current:{}}};a.Actions={Init:a.Init,HidePanel:a.HidePanel,ShowPanel:a.ShowPanel,File:a.File,Element:a.Element,Power:a.Power,Generator:a.Generator,Options:a.OptionsFunc,About:a.About,Exit:a.Exit};return a}();
Evema.Modules.Generator=function(){var a={Button:null,Init:function(){a.Button=Evema.Get("Tools:Buttons")["generator-tool"];void 0===a.Button&&console.warn('"generator-tool" button was not found in document')},Toggle:function(){var b=Evema.GetLocal(a,"Enabled");Evema.SetLocal(a,"Enabled",!b)},Options:{Standard:{enabled:!1},Current:{},Setters:{Enabled:function(a,c){if(!c||Evema.Get("Power:Enabled"))Evema.SetLocal(a,"enabled",c),c?$(a.Button).addClass("enabled"):$(a.Button).removeClass("enabled")}},
Getters:{Enabled:function(a){return Evema.GetLocal(a,"enabled")}}}};a.Actions={Init:a.Init,Toggle:a.Toggle};return a}();
Evema.Modules.Power=function(){var a={Button:null,Init:function(){a.Button=Evema.Get("Tools:Buttons")["power-tool"];void 0===a.Button&&console.warn('"power-tool" button was not found in document')},Toggle:function(){var b=Evema.GetLocal(a,"Enabled");Evema.SetLocal(a,"Enabled",!b)},Options:{Standard:{enabled:!1},Current:{},Setters:{Enabled:function(a,c){Evema.SetLocal(a,"enabled",c);c?$(a.Button).addClass("enabled"):($(a.Button).removeClass("enabled"),Evema.Set("Generator:Enabled",!1))}},Getters:{Enabled:function(a){return Evema.GetLocal(a,
"enabled")}}}};a.Actions={Init:a.Init,Toggle:a.Toggle};return a}();
Evema.Modules.Grid=function(){var a={Instance:null,Context:null,Init:function(){var b=document.getElementById("e-grid");null===b?(console.error("Evema.Core.Grid.Init error"),console.error('Can\'t find element "e-grid" in document')):(a.Instance=b,a.Context=b.getContext("2d"),Evema.SetLocal(a,"Instance",a.Instance),Evema.SetLocal(a,"Context",a.Context),a.Rebuild())},Rebuild:function(){var b=a.Instance;if(null===b)console.warn("Can't rebuild grid, the grid instance is null!");else{var c=Evema.GetLocal(a,
"Width"),d=Evema.GetLocal(a,"Height"),e=Evema.GetLocal(a,"CellWidth"),f=Evema.GetLocal(a,"CellHeight");b.width=c*e;b.height=d*f;a.Redraw()}},Redraw:function(){a.Clear();a.Draw()},Clear:function(){var b=a.Instance;if(null===b)console.warn("Can't clear grid, the grid instance is null!");else{var c=a.Context,d=Evema.GetLocal(a,"BackgroundColor");c.clearRect(0,0,b.width,b.height);document.documentElement.style.setProperty("--grid-background-color",d)}},Draw:function(){var b=a;if(null===b.Instance)console.warn("Can't draw grid, the grid instance is null!");
else{var c=b.Context,d=Evema.GetLocal(b,"Type"),e=Evema.GetLocal(b,"LineColor"),f=Evema.GetLocal(b,"CellWidth"),g=Evema.GetLocal(b,"CellHeight"),h=Evema.GetLocal(b,"Width"),k=Evema.GetLocal(b,"Height"),l=Evema.GetLocal(b,"OffsetX")%f;b=Evema.GetLocal(b,"OffsetY")%g;c.fillStyle=e;if("pixel"===d)for(d=0;d<k;d++)for(e=0;e<h;e++)c.fillRect(f*e+l,g*d+b,1,1);else console.warn('Unknown draw type "'+d+'"')}},Options:{Standard:{Instance:null,Context:null,BackgroundColor:"#D3D1BB",LineColor:"#000000",CellWidth:8,
CellHeight:8,Width:100,Height:60,Type:"pixel",OffsetX:0,OffsetY:0},Current:{}}};a.Actions={Init:a.Init,Rebuild:a.Rebuild,Redraw:a.Redraw,Clear:a.Clear,Draw:a.Draw};return a}();
Evema.Modules.ContextMenu=function(){var a={Instance:null,Init:function(){var b=a,c=Evema.Get("Grid:Instance");void 0===c?console.warn("No grid instance"):(window.addEventListener("contextmenu",function(a){a.preventDefault()},!1),window.addEventListener("click",function(a){Evema.SetLocal(b,"Visible",!1)},!1),c.oncontextmenu=function(a){a.stopPropagation();a.preventDefault();Evema.SetLocal(b,"Position",{x:a.x,y:a.y});Evema.SetLocal(b,"Visible",!0)},b.Instance=$(".context-menu")[0],b.Instance.addEventListener("click",
function(a){a.stopPropagation()}),Evema.SetLocal(b,"Instance",b.Instance))},Show:function(){Evema.SetLocal(a,"Visible",!0)},Hide:function(){Evema.SetLocal(a,"Visible",!1)},OnVisible:function(a,c){c?(c=Evema.GetLocal(a,"Position"),a.Instance.style.left=c.x+"px",a.Instance.style.top=c.y+"px",$(a.Instance).removeClass("hidden")):$(a.Instance).addClass("hidden")}};a.Actions={Init:a.Init,Show:a.Show,Hide:a.Hide};a.Options={Standard:{Instance:null,Visible:!1,Position:{x:0,y:0}},Current:{},Setters:{Visible:a.OnVisible}};
return a}();Evema.Modules.Schema=function(){var a={Init:function(){}};a.Actions={Init:a.Init};a.Options={Standard:{},Current:{}};return a}();